### ISSUE TITLE
Improve http request handling

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-airflow#131]
In some cases DAGs fail because the connection is refused. We may be hitting the server with too many requests at once. AUC is of particular concern because it has 22 collections. Each will run individually but if all are triggered the majority of them will usually fail. I suspect this is caused by too many server requests. 

Is there a way to limit the number of DAGs that run at once to a reasonable number (maybe 3?) so that providers with more than 3 collections will get harvested in batches and we don't overload provider servers?

**Comment by edsu** [comment]
If AUC seems to reliably fail we could try using the new SequentialCsvSource which will load a URL one at a time and could be customized further to sleep between requests if we want it to?

**Comment by edsu** [comment]
I just edited my AUC catalog to point at my own server (where I can watch the requests), and I can see running the DAG triggers a barrage of requests at 26 requests per second. I don't think it's unusual for a server to see this as pretty aggressive, and start blocking.

It's clear from the Airflow UI that each collection is being fetched in parallel. This is normally a good thing, but since each collection is targeting the same server I think it is problematic.

![Screen Shot 2022-09-09 at 11.50.31 AM.png](https://images.zenhubusercontent.com/61d7743b3a7b4b1a4c05fcd3/4b63331d-2153-464c-b6bf-161418bac3de)

I wonder if it might be possible to optionally configure the DAG in cases like this so that they run serially (one after the other) rather than in parallel?

**Comment by edsu** [comment]
I guess we have a choice here of making just the harvest happen serially, and then letting the remaining steps (transform, index) continue to happen in parallel?

**Comment by edsu** [comment]
After we had a chance to discuss post-standup consensus was that we'd try something that is not diagrammed: making each collection its own DAG so that they can be scheduled to not overlap. This will add some complexity to the Airflow homepage, but should be simpler from a coding perspective, and should give us a lot of flexibility.

The idea would be to introduce a Provider Intake config setting that would cause the collections to be separate DAGS instead of TaskGroups within the same DAG.
