### ISSUE TITLE
Need to make resumption token configurable in OAI-PMH driver

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme-airflow#173]
At least one collection uses resumption tokens which are configurable in Sickle like `records = sickle.ListRecords(resumptionToken='0mods_no_ocr')`. We need to pull this field from the config when available and, if not in the config, continue behaving as is.

**Comment by edsu** [comment]
I think we discovered in huddle yesterday that if metadataPrefix is used, then hard coding the resumption token should not be needed?

https://api.qdl.qa/api/oaipmh?verb=ListRecords&metadataPrefix=mods_no_ocr

**Comment by aaron-collier** [comment]
@jacobthill do you think the metadataPrefix is sufficient here since so far QNL is the only provider we have with that resumptionToken concern?

**Comment by edsu** [comment]
Yes, I think it makes more sense from an OAI-PMH perspective for us to configure `metadataPrefix` in the catalog rather than hard coding a resumption token. Should we re-title this issue to reflect that?

To get QNL to work we will need to adjust the `dlme_airflow.drivers.OaiXmlSource` to handle the mods xml, but we have #175 for that (which I picked up).

**Comment by jacobthill** [comment]
Sorry for the delay, I agree with @edsu

**Comment by aaron-collier** [comment]
@edsu thank you, great info. closing. If we find we may need this, we can revisit later.
