### ISSUE TITLE
Investigate improving docker image build performance

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dlme-airflow#211]
The docker image build is quite slow. It may be improved with docker caching/step strategies.

**Comment by edsu** [comment]
I noticed that it spends a lot of time when poetry is installing things and was wondering if this issue might be relevant:

https://github.com/python-poetry/poetry/issues/2094

I haven't digested the thread fully yet to see if there is a good solution, but I think poetry is having to do extra work because of how our `pyproject.toml` is set up?

**Comment by dswalter** [comment]
Try running `poetry update -vvv` and double-check whether there are any of the known aws provider issues that are plaguing you. Then pin those (aws-cli, boto3, etc.) to something very recent. Old versions of those packages don't have required metadata, so you have to download the wheel file to check it, and that takes a long time.

**Comment by edsu** [comment]
Thanks for the help @dswalter! 

It turns out most of our pain was from not pinning httpx, once adjusted the build time greatly improved: 

```
before: 06:23.23
after:  00:48.840
```
